export const FETCH_RESERVATIONS_DATA = 'FETCH_RESERVATIONS_DATA';

export const FILTER_ENTRIES = 'FILTER_ENTRIE';

export const FETCH_MENU_DATA = 'FETCH_MENU_DATA';

export const TOGGLE_MEAL = 'TOGGLE_MEAL';
