@startuml Auth

class Auth implements Component {
  {static} hasRequiredRole() : bool
  ensureAuth() : void
  render()
}

class ConcreteComponent implements Component {
  ownMethod()
  render()
}

interface Component {
  componentDidUpdate() : void
  componentDidMount() : void
  componentShouldUpdate() : void
  render()
}

note right of Auth : HOC component

Component <---o Auth


@enduml