@startuml react-redux
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Aqua-CadetBlue

title Interazione react-redux 



node "Redux Store" as Store

node Reducer
node "Dispatched Action" as Dispatch

node ReactComponent as Component {
	node "State" as Browser
  node "Redux props" as Rprops
}
node HTMLView

Dispatch --> Reducer : action 
Reducer --> Store
Store --> Component : state
Component --> Dispatch
Component <--> HTMLView

@enduml